name: contact_list_example
description: Demonstrates how to use the contact_list plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  contact_list:
    path: ../

  cupertino_icons: 1.0.0
  alphabet_list_scroll_view: 1.0.6
  draggable_scrollbar: 0.0.4
  permission_handler: 5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
